language: rust

os:
  - linux
  - osx
  - windows

rust:
  - beta
  - stable

before_script:
  - rustup component add rustfmt

script:
  - cargo fmt --all -- --check
  - cargo build
  - cargo test
  - if [ "$TRAVIS_OS_NAME" != "windows" ]; then cargo test --release --features=no-panic; fi
